<?php

include_once __DIR__ . '/base/Process.php';
include_once __DIR__ . '/base/StringGen.php';
include_once('UserNameGen.php');
include_once('UserEmailGen.php');
include_once('UserPasswordGen.php');
include_once('UserPhoneGen.php');
include_once('LoginGen.php');
include_once('PasswordGen.php');
include_once('NewUserNameGen.php');
include_once('NewUserEmailGen.php');
include_once('NewUserPasswordGen.php');
include_once('NewUserPhoneGen.php');
include_once __DIR__ . '/base/NewUserBirthDateGen.php';
include_once __DIR__ . '/base/NewUserGenderGen.php';
include_once __DIR__ . '/base/NewUserNewsGen.php';
include_once('NewUserNotificationsGen.php');
include_once __DIR__ . '/base/IncorrectUserEmailGen.php';
include_once('IncorrectUserPasswordGen.php');
include_once __DIR__ . '/base/IncorrectUserNameGen.php';
include_once('IncorrectUserPhoneGen.php');
include_once('IncorrectLoginGen.php');
include_once('IncorrectPasswordGen.php');
include_once('IncorrectNewUserNameGen.php');
include_once('IncorrectNewUserEmailGen.php');
include_once('IncorrectNewUserPasswordGen.php');
include_once('IncorrectNewUserPhoneGen.php');
include_once __DIR__ . '/base/IncorrectNewUserBirthDateGen.php';
include_once __DIR__ . '/base/IncorrectNewUserGenderGen.php';
include_once __DIR__ . '/base/IncorrectNewUserNewsGen.php';
include_once('IncorrectNewUserNotificationsGen.php');
include_once  __DIR__ . '/base/GetFileDataByRegExp.php';
include_once('ArticleGen.php');
include_once('BarcodeGen.php');
include_once __DIR__ . '/base/IncorrectArticleGen.php';
include_once __DIR__ . '/base/IncorrectBarcodeGen.php';
include_once('NonExistsBarcodeGen.php');